### ISSUE TITLE
M1.arm64  macOS 12.1 not work

### ISSUE THREAD

**Issue by apa7** [eisenxp/macos-golink-wrapper#7]
Golang took a long time to compile and finally failed

Traceback (most recent call last):
  File "/usr/local/go/pkg/tool/darwin_arm64/original_link", line 14, in <module>
    output = subprocess.check_output([os.path.dirname(__file__) + '/' + original_link_file] + sys.argv[1:], cwd=os.getcwd())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
BlockingIOError: [Errno 35] Resource temporarily unavailable

**Comment by vaf714** [comment]
The same problem, did you solve it?

**Comment by shixinlu0730** [comment]
The same problem, did you solve it?
